name: flokk
description: A fresh and modern Google Contacts manager that integrates with GitHub and Twitter.
version: 1.1.0
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # animations: ^2.0.0-nullsafety.0
  # cupertino_icons: ^1.0.2
  collection: ^1.15.0
  desktop_window: ^0.4.0
  # dartx: ^0.7.1
  # dotted_border: ^2.0.0-nullsafety.0
  draggable_scrollbar: ^0.1.0
  # # file_selector: ^0.8.2
  # # file_selector_windows: ^0.0.2
  # # file_selector_macos: ^0.0.4
  # # file_selector_linux: ^0.0.2
  # # file_selector_web: ^0.8.1
  # flutter_hooks: ^0.16.0
  # github: ^8.1.0
  # google_sign_in: ^5.0.1
  # googleapis: ^2.0.0
  # http: ^0.13.6
  # html: ^0.15.0
  # image: ^3.0.2
  # intl: ^0.17.0
  # json_annotation: ^4.0.1
  package_info: ^2.0.0
  # path: ^1.8.0
  # path_provider: ^2.0.1
  # provider: ^5.0.0
  # shared_preferences: ^2.0.5
  # sized_context: ^1.0.0-nullsafety
  # statsfl: ^2.0.1-nullsafety
  # styled_widget: ^0.3.1
  textstyle_extensions: ^2.0.0-nullsafety
  # timeago: ^3.0.2
  # tuple: ^2.0.0
  # universal_platform: ^1.0.0-nullsafety
  # url_launcher: ^6.0.3
  # xdg_directories: ^0.2.0

  # # NEW
  # file_selector: ^1.0.3
  # file_selector_windows: ^0.9.3+1
  # file_selector_macos: ^0.9.4
  # file_selector_linux: ^0.9.2+1
  # file_selector_web: ^0.9.4+1
  animations: ^2.0.11
  archive: ^3.6.1
  args: ^2.5.0
  async: ^2.11.0
  build: ^2.4.1
  build_config: ^1.1.1
  build_daemon: ^4.0.2
  build_resolvers: ^2.4.2
  # built_collection: ^5.1.1
  built_value: ^8.9.2
  charcode: ^1.3.1
  checked_yaml: ^2.0.3
  cli_util: ^0.4.1
  clock: ^1.1.1
  code_builder: ^4.10.0
  convert: ^3.1.1
  cross_file: ^0.3.4+1
  crypto: ^3.0.3
  csslib: ^1.0.0
  cupertino_icons: ^1.0.8
  dart_style: ^2.3.6
  dartx: ^1.2.0
  dotted_border: ^2.1.0
  ffi: ^2.1.2
  file: ^7.0.0
  file_selector: ^1.0.3
  file_selector_android: ^0.5.1+2
  file_selector_ios: ^0.5.3
  file_selector_linux: ^0.9.2+1
  file_selector_macos: ^0.9.4
  file_selector_platform_interface: ^2.6.2
  file_selector_web: ^0.9.4+1
  file_selector_windows: ^0.9.3+1
  fixnum: ^1.1.0
  flutter_hooks: ^0.20.5
  github: ^9.24.0
  glob: ^2.1.2
  google_sign_in: ^6.2.1
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4
  googleapis: ^13.1.0
  graphs: ^2.3.1
  html: ^0.15.4
  http: ^1.2.1
  http_multi_server: ^3.2.1
  http_parser: ^4.0.2
  image: ^4.2.0
  intl: ^0.19.0
  io: ^1.0.4
  js: ^0.7.1
  json_annotation: ^4.9.0
  lint: ^1.5.3
  logging: ^1.2.0
  matcher: ^0.12.16+1
  material_color_utilities: ^0.8.0
  meta: 1.12.0  # Aligning with Flutter SDK version
  mime: ^1.0.5
  package_config: ^2.1.0
  path: ^1.9.0
  path_drawing: ^1.0.1
  path_parsing: ^1.0.1
  path_provider: ^2.1.3
  path_provider_android: ^2.2.5
  path_provider_ios: ^2.0.11
  path_provider_linux: ^2.2.1
  path_provider_macos: ^2.0.7
  path_provider_platform_interface: ^2.1.2
  path_provider_windows: ^2.2.1
  pedantic: ^1.11.1
  petitparser: ^6.0.2
  platform: ^3.1.5
  plugin_platform_interface: ^2.1.8
  pool: ^1.5.1
  process: ^5.0.2
  provider: ^6.1.2
  pub_semver: ^2.1.4
  pubspec_parse: ^1.3.0
  quiver: ^3.2.1
  shared_preferences: ^2.2.3
  shared_preferences_linux: ^2.3.2
  shared_preferences_macos: ^2.0.5
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.3.0
  shared_preferences_windows: ^2.3.2
  shelf: ^1.4.1
  shelf_web_socket: ^2.0.0
  sized_context: ^1.0.0+4
  source_gen: ^1.5.0
  source_span: ^1.10.0
  stack_trace: ^1.11.1
  statsfl: ^2.3.0
  stream_channel: ^2.1.2
  stream_transform: ^2.1.0
  string_scanner: ^1.2.0
  styled_widget: ^0.3.1
  term_glyph: ^1.2.1
  time: ^2.1.4
  timeago: ^3.6.1
  timing: ^1.0.1
  tuple: ^2.0.2
  typed_data: ^1.3.2
  universal_platform: ^1.1.0
  url_launcher: ^6.3.0
  url_launcher_linux: ^3.1.1
  url_launcher_macos: ^3.2.0
  url_launcher_platform_interface: ^2.3.2
  url_launcher_web: ^2.3.1
  url_launcher_windows: ^3.1.1
  watcher: ^1.1.0
  web_socket_channel: ^3.0.0
  win32: ^5.5.1
  xdg_directories: ^1.0.4
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.11
  build_runner_core: ^7.3.1
  json_serializable: ^6.8.0  # Generate JSON parsers: flutter pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  platform: ^3.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 200
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 200
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 800

    - family: OpenSansEmoji
      fonts:
        - asset: assets/fonts/OpenSansEmoji.ttf

  assets:
    - assets/images/
    - assets/images/birds/
    - assets/images/flokk-logo.svg
    - assets/images/avatars/
    - assets/icons/

